### ISSUE TITLE
SSO/OIDC authentication broken after upgrading from 6.7.19 to 6.8.4

### ISSUE THREAD

**Issue by jercherng** [OpenCTI-Platform/opencti#12704]
## Description

**Issue:** During OIDC authentication callbacks, `req.body` is `undefined`, causing:
- JavaScript tries to access `undefined.RelayState`
- This throws `TypeError: Cannot read properties of undefined`
- Authentication fails and users cannot log in via SSO
- User is greeted with 504 Gateway Time-out

## Environment

1. Linux
2. OpenCTI version: 6.7.19 to 6.8.4
3. OpenCTI client: backend (graphql)
4. Other environment details: SSO via OIDC

## Reproducible Steps

Steps to create the smallest reproducible scenario:
1. Login via SSO
2. Complete SSO flow
3. Stuck without redirecting

## Expected Output

1. Redirect to dashboard `<insert-public-domain-here>/dashboard`
2. No RelayState error
3. No localhost:4000 redirect
4. No 504 timeout

## Actual Output
1. Get Error Message:
    ```
    {
        "category": "APP",
        "level": "error",
        "message": "[OPENCTI] Engine unhandled rejection",
        "reason": "TypeError: Cannot read properties of undefined (reading 'RelayState')\n    at /opt/opencti/build/back.js:4201:12609\n    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)",
        "source": "backend",
        "timestamp": "2025-10-11T22:31:25.263Z",
        "version": "6.8.4"
    }
    ```
3. Front-end responds with 504 Gateway Time-out
4. Refreshing the page actually takes you to the dashboard (authentication successful)

## Additional Information
---

The error occurs in the authentication callback route at line 493 of the source:

```javascript
// In httpPlatform.js line 493
const referer = req.body.RelayState ?? req.session.referer;
```

The code assumes `req.body` always exists, but OIDC callbacks may not have a body.

OIDC authentication flow:
1. User clicks "Login with SSO"
2. Browser redirects to identity provider
3. Identity provider authenticates user
4. Identity provider redirects back to `/auth/oic/callback`
5. **Problem:** Callback data location varies by provider:
   - SAML: Uses `req.body.RelayState`
   - OIDC: Often uses `req.query` or session storage
   - Some providers: Don't send state at all

Cursor-assisted RCA.

**Comment by marieflorescontact** [comment]
may be related to this PR: https://github.com/OpenCTI-Platform/opencti/pull/12542

**Comment by labo-flg** [comment]
We have merged a short PR https://github.com/OpenCTI-Platform/opencti/pull/12743 to solve this critical bug quickly.
We can still consider https://github.com/OpenCTI-Platform/opencti/pull/12705 for review, as it introduces more tests.

**Comment by NexusFuzzy** [comment]
I upgraded to 6.8.5 but the error persists and SAML can't be used to log in. Let me know if I can aid with logs

**Comment by xfournet** [comment]
@NexusFuzzy  could you provide more information on the error you encounter with version 6.8.5 ?

**Comment by NexusFuzzy** [comment]
Hi, when logging in via SAML after successful authentication I get redirected to /dashboard but instead of the /dashboard content I see the login page. Since this issue was introduced with the same version as the OIDC bug fixed above, I suspect that it might have the same root cause.

**Comment by CelineSebe** [comment]
@alice-debra, should we open a new issue for SAML problem or modify this one?

**Comment by alice-debra** [comment]
> [@alice-debra](https://github.com/alice-debra), should we open a new issue for SAML problem or modify this one?

Yes, we can :)
