### ISSUE TITLE
Dashboard connection issues with docker

### ISSUE THREAD

**Issue by navhits** [OpenCTI-Platform/opencti#464]
## Description

After running ```docker-compose --compatibility up``` the dashboard at localhost does not work well. After logging in the dashboard is displayed. Clicking on something brings up a blank page saying "ERROR"

## Environment

Docker version 19.03.5, build 633a0ea

## Reproducible Steps

1. Run ```docker-compose --compatibility up``` after following instructions from #418 
2. I waited for almost 30 minutes for errors to clear, but it did not.
3. Logged into the dashboard and tried to navigate around
4. Gave an error

## Expected Output

Expected to run successfully

## Actual Output

A blank screen with a word "ERROR" 

## Additional information

[![Screenshot](https://i.imgur.com/jw9Bs0q.png?1)](https://i.imgur.com/jw9Bs0q)

**Comment by graememeyer** [comment]
Hi @NAVHITS if I remember correctly, the port number is referenced in the config file at least twice - might be worth double checking that you've changed them all

**Comment by SamuelHassine** [comment]
Hi @NAVHITS ,

Coud you please provide here the exact content of your `docker-compose.yml` file? We do not have any default docker-compose with the port 4000.

Kind regards,
Samuel

**Comment by navhits** [comment]
@SamuelHassine 
This was suggested by @graememeyer [here](https://github.com/OpenCTI-Platform/opencti/issues/418#issuecomment-581164541) in #418

Take a look at it
```
version: '3'
services:
  grakn:
    image: graknlabs/grakn:1.6.2
    ports:
      - 48555:48555 
    volumes:
      - grakndata:/grakn-core-all-linux/server/db
    restart: always
  redis:
    image: redis:5.0.5
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  minio:
    image: minio/minio:RELEASE.2019-10-12T01-39-57Z
    volumes:
      - s3data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: NewAccess19191919
      MINIO_SECRET_KEY: NewAccess19191919
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  rabbitmq:
    image: rabbitmq:3.7.17-management
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest    
    restart: always
  opencti:
    image: opencti/platform:rolling
    environment:
      - APP__PORT=4000
      - APP__ADMIN__EMAIL=admin@opencti.io
      - APP__ADMIN__PASSWORD=admin
      - APP__ADMIN__TOKEN=29a29074-20ae-4159-a191-88d4d54b69b5
      - APP__LOGS=./logs
      - APP__REACTIVE=true
      - APP__COOKIE_SECURE=false
      - GRAKN__HOSTNAME=grakn
      - GRAKN__PORT=48555
      - GRAKN__TIMEOUT=30000
      - REDIS__HOSTNAME=redis
      - REDIS__PORT=6379
      - ELASTICSEARCH__URL=http://elasticsearch:9200
      - MINIO__ENDPOINT=minio
      - MINIO__PORT=9000
      - MINIO__USE_SSL=false
      - MINIO__ACCESS_KEY=NewAccess19191919
      - MINIO__SECRET_KEY=NewAccess19191919
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__PORT_MANAGEMENT=15672
      - RABBITMQ__MANAGEMENT_SSL=false
      - RABBITMQ__USERNAME=guest
      - RABBITMQ__PASSWORD=guest
    ports:
      - "4000:4000"
    depends_on:
      - grakn
      - redis
      - elasticsearch
      - minio
      - rabbitmq
    restart: always
  worker:
    image: opencti/worker:rolling
    environment:
      - OPENCTI_URL=http://opencti:4000
      - OPENCTI_TOKEN=29a29074-20ae-4159-a191-88d4d54b69b5
      - WORKER_LOG_LEVEL=info
    depends_on:
      - opencti
    deploy:
      mode: replicated
      replicas: 1
    restart: always
  connector-export-file-stix:
    image: opencti/connector-export-file-stix:rolling
    environment:
      - OPENCTI_URL=http://opencti:4000
      - OPENCTI_TOKEN=29a29074-20ae-4159-a191-88d4d54b69b5
      - CONNECTOR_ID=79f6b85e-bbbb-484a-b475-a97c1bc6895d
      - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
      - CONNECTOR_NAME=ExportFileStix2
      - CONNECTOR_SCOPE=application/json
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_LOG_LEVEL=info
    restart: always
  connector-export-file-csv:
    image: opencti/connector-export-file-csv:rolling
    environment:
      - OPENCTI_URL=http://opencti:4000
      - OPENCTI_TOKEN=29a29074-20ae-4159-a191-88d4d54b69b5
      - CONNECTOR_ID=97c8a12d-703f-429d-9ab1-26ef1843f7f8
      - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
      - CONNECTOR_NAME=ExportFileCsv
      - CONNECTOR_SCOPE=application/csv
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_LOG_LEVEL=info
    restart: always    
  connector-import-file-stix:
    image: opencti/connector-import-file-stix:rolling
    environment:
      - OPENCTI_URL=http://opencti:4000
      - OPENCTI_TOKEN=29a29074-20ae-4159-a191-88d4d54b69b5
      - CONNECTOR_ID=f023a2f6-cfd4-43ed-8649-d02ea1541266
      - CONNECTOR_TYPE=INTERNAL_IMPORT_FILE
      - CONNECTOR_NAME=ImportFileStix2
      - CONNECTOR_SCOPE=application/json
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_LOG_LEVEL=info
    restart: always    
  connector-opencti:
    image: opencti/connector-opencti:rolling
    environment:
      - OPENCTI_URL=http://opencti:4000
      - OPENCTI_TOKEN=29a29074-20ae-4159-a191-88d4d54b69b5
      - CONNECTOR_ID=4ae2f632-e261-4bc3-9ddc-9de7d5f89a7f
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=OpenCTI
      - CONNECTOR_SCOPE=identity,sector,region,country,city
      - CONNECTOR_CONFIDENCE_LEVEL=5
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_LOG_LEVEL=info
      - CONFIG_SECTORS_FILE_URL=https://raw.githubusercontent.com/OpenCTI-Platform/datasets/master/data/sectors.json
      - CONFIG_GEOGRAPHY_FILE_URL=https://raw.githubusercontent.com/OpenCTI-Platform/datasets/master/data/geography.json
      - CONFIG_INTERVAL=7 # Days
    depends_on:
      - opencti
    restart: always
  connector-mitre:
    image: opencti/connector-mitre:rolling
    environment:
      - OPENCTI_URL=http://opencti:4000
      - OPENCTI_TOKEN=29a29074-20ae-4159-a191-88d4d54b69b5
      - CONNECTOR_ID=00888f62-ddc4-40cb-83b5-22256c52c1b2
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=MITRE ATT&CK
      - CONNECTOR_SCOPE=identity,attack-pattern,course-of-action,intrusion-set,malware,tool
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_LOG_LEVEL=info
      - MITRE_ENTERPRISE_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json
      - MITRE_PRE_ATTACK_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/pre-attack/pre-attack.json
      - MITRE_INTERVAL=7 # Days
    restart: always     
volumes:
  grakndata:
  esdata:
  s3data:

```

**Comment by navhits** [comment]
> Hi @NAVHITS if I remember correctly, the port number is referenced in the config file at least twice - might be worth double checking that you've changed them all

Looked at it already. I've changed those

**Comment by SamuelHassine** [comment]
@NAVHITS: could you please retry and follow the new version of the [deployment documentation](https://opencti-platform.github.io/docs/installation/auto)? I think your problem is now solved.

**Comment by navhits** [comment]
I hope I am doing things right. I followed the docs. Based on that I changed the parameters as in docs. Added the ```vm.max_map_count``` as well. I am still facing issues. Open CTI workers are always down for a very long time. I tried manually starting them but they keep restarting due to some unknown issues. The docker compose file I modified is here.
```
version: '3'
services:
  grakn:
    image: graknlabs/grakn:1.6.2
    ports:
      - 48555:48555 
    volumes:
      - grakndata:/grakn-core-all-linux/server/db
    restart: always
  redis:
    image: redis:5.0.5
    restart: always
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    volumes:
      - esdata:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    restart: always
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
  minio:
    image: minio/minio:RELEASE.2019-10-12T01-39-57Z
    volumes:
      - s3data:/data
    ports:
      - "9000:9000"
    environment:
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY}
    command: server /data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  rabbitmq:
    image: rabbitmq:3.7.17-management
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}    
    restart: always
  opencti:
    image: opencti/platform:3.0.3
    environment:
      - APP__PORT=8080
      - APP__ADMIN__EMAIL=${OPENCTI_ADMIN_EMAIL}
      - APP__ADMIN__PASSWORD=${OPENCTI_ADMIN_PASSWORD}
      - APP__ADMIN__TOKEN=2d4b50cc-4f46-40ac-86dc-840deb99c2ef
      - APP__LOGS_LEVEL=error
      - APP__LOGS=./logs
      - APP__REACTIVE=true
      - APP__COOKIE_SECURE=false
      - GRAKN__HOSTNAME=grakn
      - GRAKN__PORT=48555
      - GRAKN__TIMEOUT=30000
      - REDIS__HOSTNAME=redis
      - REDIS__PORT=6379
      - ELASTICSEARCH__URL=http://elasticsearch:9200
      - MINIO__ENDPOINT=minio
      - MINIO__PORT=9000
      - MINIO__USE_SSL=false
      - MINIO__ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO__SECRET_KEY=${MINIO_SECRET_KEY}
      - RABBITMQ__HOSTNAME=rabbitmq
      - RABBITMQ__PORT=5672
      - RABBITMQ__PORT_MANAGEMENT=15672
      - RABBITMQ__MANAGEMENT_SSL=false
      - RABBITMQ__USERNAME=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ__PASSWORD=${RABBITMQ_DEFAULT_PASS}
      - PROVIDERS__LOCAL__STRATEGY=LocalStrategy
    ports:
      - "8080:8080"
    depends_on:
      - grakn
      - redis
      - elasticsearch
      - minio
      - rabbitmq
    restart: always
  worker:
    image: opencti/worker:3.0.3
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=2d4b50cc-4f46-40ac-86dc-840deb99c2ef
      - WORKER_LOG_LEVEL=info
    depends_on:
      - opencti
    deploy:
      mode: replicated
      replicas: 3
    restart: always
  connector-export-file-stix:
    image: opencti/connector-export-file-stix:3.0.3
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=2d4b50cc-4f46-40ac-86dc-840deb99c2ef
      - CONNECTOR_ID=2d4b50cc-4f46-40ac-86dc-840deb99c2ef
      - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
      - CONNECTOR_NAME=ExportFileStix2
      - CONNECTOR_SCOPE=application/json
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_LOG_LEVEL=info
    restart: always
  connector-export-file-csv:
    image: opencti/connector-export-file-csv:3.0.3
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=2d4b50cc-4f46-40ac-86dc-840deb99c2ef
      - CONNECTOR_ID=2d4b50cc-4f46-40ac-86dc-840deb99c2ef
      - CONNECTOR_TYPE=INTERNAL_EXPORT_FILE
      - CONNECTOR_NAME=ExportFileCsv
      - CONNECTOR_SCOPE=application/csv
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_LOG_LEVEL=info
    restart: always    
  connector-import-file-stix:
    image: opencti/connector-import-file-stix:3.0.3
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=2d4b50cc-4f46-40ac-86dc-840deb99c2ef
      - CONNECTOR_ID=2d4b50cc-4f46-40ac-86dc-840deb99c2ef
      - CONNECTOR_TYPE=INTERNAL_IMPORT_FILE
      - CONNECTOR_NAME=ImportFileStix2
      - CONNECTOR_SCOPE=application/json
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_LOG_LEVEL=info
    restart: always
  connector-import-file-pdf-observables:
    image: opencti/connector-import-file-pdf-observables:3.0.3
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=2d4b50cc-4f46-40ac-86dc-840deb99c2ef
      - CONNECTOR_ID=2d4b50cc-4f46-40ac-86dc-840deb99c2ef
      - CONNECTOR_TYPE=INTERNAL_IMPORT_FILE
      - CONNECTOR_NAME=ImportFilePdfObservables
      - CONNECTOR_SCOPE=application/pdf
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_LOG_LEVEL=info
      - PDF_OBSERVABLES_CREATE_INDICATOR=False
    restart: always    
  connector-opencti:
    image: opencti/connector-opencti:3.0.3
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=2d4b50cc-4f46-40ac-86dc-840deb99c2ef
      - CONNECTOR_ID=2d4b50cc-4f46-40ac-86dc-840deb99c2ef
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=OpenCTI
      - CONNECTOR_SCOPE=identity,sector,region,country,city
      - CONNECTOR_CONFIDENCE_LEVEL=5
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_LOG_LEVEL=info
      - CONFIG_SECTORS_FILE_URL=https://raw.githubusercontent.com/OpenCTI-Platform/datasets/master/data/sectors.json
      - CONFIG_GEOGRAPHY_FILE_URL=https://raw.githubusercontent.com/OpenCTI-Platform/datasets/master/data/geography.json
      - CONFIG_INTERVAL=7 # Days
    restart: always
  connector-mitre:
    image: opencti/connector-mitre:3.0.3
    environment:
      - OPENCTI_URL=http://opencti:8080
      - OPENCTI_TOKEN=2d4b50cc-4f46-40ac-86dc-840deb99c2ef
      - CONNECTOR_ID=2d4b50cc-4f46-40ac-86dc-840deb99c2ef
      - CONNECTOR_TYPE=EXTERNAL_IMPORT
      - CONNECTOR_NAME=MITRE ATT&CK
      - CONNECTOR_SCOPE=identity,attack-pattern,course-of-action,intrusion-set,malware,tool,report
      - CONNECTOR_CONFIDENCE_LEVEL=3
      - CONNECTOR_UPDATE_EXISTING_DATA=true
      - CONNECTOR_LOG_LEVEL=info
      - MITRE_ENTERPRISE_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/enterprise-attack/enterprise-attack.json
      - MITRE_PRE_ATTACK_FILE_URL=https://raw.githubusercontent.com/mitre/cti/master/pre-attack/pre-attack.json
      - MITRE_INTERVAL=7 # Days
    restart: always
volumes:
  grakndata:
  esdata:
  s3data:
```

**Comment by SamuelHassine** [comment]
Are you still encounter some problems to start OpenCTI with the latest version?

**Comment by navhits** [comment]
I'm yet to try this. Will look at it over this weekend. Thank you

**Comment by SamuelHassine** [comment]
I close this issue due to inactivity. Feel free to re-open it if you still have a problem!
